language: python

python:
    - "3.6"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

services:
    - docker

before_install:
    - "pip3 install --upgrade pip"
    - "pip install -r requirements.txt"

install:

script:
    - make tests

notifications:
  slack: docker-for-ed:Oxi5wULOaqdybcPC9kdgdLwj
