#!/usr/bin/awk -f
# this file preprocesses HTML files to put in includes

BEGIN {
    # Need to set these variables in ENV
    template_path = ENVIRON["TEMPLATE_DIR"]
    quiz_path = ENVIRON["QUIZ_DIR"]
    markdown_path = ENVIRON["MARKDOWN_DIR"]
}

/<html>/ {
    print "<html>"
    print "<!-- THIS FILE WAS GENERATED BY A SCRIPT: DO NOT EDIT IT! -->"
    next
}

/<!-- *include/ {
    file = $2

    # file has a forward slash in it, leave it alone:
    if(!match($2, /\//)) {
    # if file starts with 'quiz' use quiz_path not template_path
        if (quiz_path != "" && match($2, /quiz/)) {
            file = quiz_path "/" $2
        }
        # if file is a markdown, then render first.
        else if (match(file, ".*\.md$")){
            if(markdown_path!=""){
                file = markdown_path "/" $2
            }
           cmd = "python3 ./render_md.py"
           cmd | getline file
           status = close(cmd)
           if(status ==0){
                s = "<p>We attempted to render markdown file from " file " but failed.</p>"
                print s > "/dev/stderr"
                print s
           }
        }
        # if file is a template.
        else{
            if(template_path!=""){
                file = template_path "/" $2
            }
        }
    }
    # if file is a markdown file, then render first.
    if(match(file, ".*\.md$")){
        cmd = "python3 ./render_md.py"
        cmd | getline file
        close(file)
    }
    i = 0
    while((getline < file ) > 0 ) {
    	print $0
        i++
    }
    close(file)
    if (i == 0) {
        s = "<p>We attempted to read from " file " but failed.</p>"
        print s > "/dev/stderr"
        print s
    }
    next
}

{ print }
