import mistune
import jinja2
import os
import sys
from pathlib import Path

text = """
"""
renderer = mistune.Renderer(escape=False, hard_wrap=False)
# use this renderer instance
markdown = mistune.Markdown(renderer=renderer)
res = markdown(text)
# print(res)

cur_path = Path(os.path.abspath(os.path.dirname(sys.argv[0])))
print(cur_path)

for file in cur_path.glob('*.tpl'):
    print("Rendering " + file.name)
    md = ''
    TEMPLATE_FILE = open(file, 'r')
    TEMPLATE = TEMPLATE_FILE.read()
    md_file = file.with_suffix('.md')
    if os.path.exists(md_file):
        print("Rendering " + md_file.name)
        md = markdown(open(md_file, 'r').read())
    ptml = jinja2.Template(TEMPLATE).render(markdown_content=md)
    ptml_file = open(file.with_suffix('.ptml'), 'w+')
    ptml_file.write("<!-- THIS FILE WAS GENERATED BY A SCRIPT: DO NOT EDIT IT! -->\n")
    ptml_file.write(ptml)
    print("Generating " + ptml_file.name)
    ptml_file.close()
