import mistune
import jinja2
import os
import sys
from pathlib import Path

text = """
"""
renderer = mistune.Renderer(escape=False, hard_wrap=False)
# use this renderer instance
markdown = mistune.Markdown(renderer=renderer)
res = markdown(text)
# print(res)

cur_path = Path(os.path.abspath(os.path.dirname(sys.argv[0])))
print(cur_path)

for file in cur_path.glob('*.tpl'):
    md = ''
    TEMPLATE_FILE = open(file, 'r')
    TEMPLATE = TEMPLATE_FILE.read()
    print(1)
    md_file = file.with_suffix('.md')
    print(md_file)
    if os.path.exists(md_file):
        md = markdown(open(md_file, 'r').read())
    ptml = jinja2.Template(TEMPLATE).render(markdown_content=md)
    ptml_file = open(file.with_suffix('.ptml'),'w+')
    ptml_file.write("<!-- THIS FILE WAS GENERATED BY A SCRIPT: DO NOT EDIT IT! -->")
    ptml_file.write(ptml)
    ptml_file.close()

#
# file_path = os.path.relpath('flask.tpl', cur_path)
#
# print(file_path)
#
# TEMPLATE_FILE = open(file_path, 'r')
# TEMPLATE = TEMPLATE_FILE.read()
# md = res
# ptml = jinja2.Template(TEMPLATE).render(markdown_content=md)
# print(ptml)
