#!/bin/sh

kill -9 $(ps -e | grep slave_manager | awk -F' ' '{print $1}')

CLEAN_IDS=$(docker ps -a | grep gcallah/dc | awk -F' ' '{print $1}')
docker stop $CLEAN_IDS
docker rm $CLEAN_IDS

rm -rf ~/dc/