start-xv6:
	git clone https://github.com/mit-pdos/xv6-public.git && docker run --rm -it -v `pwd`/xv6-public:/home/xv6 --name xv6 xv6

run-xv6:
	docker run --rm -it -v `pwd`/xv6-public:/home/xv6 --name xv6 xv6